apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.port }}
